version: 2
jobs:
  build-and-push:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: docker build -t registry.gitlab.com/lascuolaopensource/join-frontend-test | echo $DOCKER_PASS | docker login -u $DOCKERUSER --password-stdin | docker push registry.gitlab.com/lascuolaopensource/join-frontend-test
workflows:
  version: 2
  deploy:
    jobs:
      - build-and-push
