version: 2
jobs:
  build-and-push:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: docker build -t lascuolaopensource/join-frontend-test:latest .
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin | docker push lascuolaopensource/join-frontend-test:latest
workflows:
  version: 2
  deploy:
    jobs:
      - build-and-push
