version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    environment:
      FOO: bar
    steps:
      - checkout
      - run: 
          name: "echo an env var that is part of our context"
          command: |
            echo $FOO
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run config 
            - run: npx ng build -prod -aot
workflows:
    build-and-test:
      jobs:
        - build-and-test
