version: 2
jobs:
  build-and-push:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: docker build -t registry.gitlab.com/lascuolaopensource/join-frontend-test .
      - run: echo $DOCKER_PASS | docker login -u $DOCKERUSER --password-stdin
      - run: docker push registry.gitlab.com/lascuolaopensource/join-frontend-test
workflows:
  version: 2
  deploy:
    jobs:
      - build-and-push
